theme: minima
title: About Erik Wei
author: Erik Wei
email: ewei@ebnet.org
image: https://raw.githubusercontent.com/leaflet12/github-pages-with-jekyll/main/unnamed.jpg

# social links
twitter_username: aidaween_
github_username: leaflet12
instagram_username: leaflet.12

show_excerpts: true # set to false to remove excerpts on the homepage
