theme: minima
title: About Erik Wei
author: Erik Wei
email: ewei@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  18k Subscribers on YouTube
  NJ High School Tennis Group IV State Champions
  NJSIAA Scholar Athlete

# social links
twitter_username: aidaween_
github_username: leaflet12
instagram_username: leaflet.12

show_excerpts: true # set to false to remove excerpts on the homepage
